export const recentClips = [
  {
    id: 'c1',
    title: 'Insane 4K Ace',
    game: 'Valorant',
    duration: '0:24',
    size: '89 MB',
    ago: '2 min ago',
    visibility: 'public',
    gradient: 'linear-gradient(145deg, #3d1f3d, #1a2a4a)',
  },
  {
    id: 'c2',
    title: 'Clutch 1v3',
    game: 'Counter-Strike 2',
    duration: '0:41',
    size: '112 MB',
    ago: '18 min ago',
    visibility: 'private',
    gradient: 'linear-gradient(145deg, #1f2d3d, #2d1f1f)',
  },
  {
    id: 'c3',
    title: 'Squad wipe',
    game: 'Apex Legends',
    duration: '0:33',
    size: '98 MB',
    ago: '1 hr ago',
    visibility: 'public',
    gradient: 'linear-gradient(145deg, #1a3d2e, #2d2438)',
  },
  {
    id: 'c4',
    title: 'Redirect read',
    game: 'Rocket League',
    duration: '0:18',
    size: '54 MB',
    ago: '3 hr ago',
    visibility: 'public',
    gradient: 'linear-gradient(145deg, #2d2510, #1a2840)',
  },
  {
    id: 'c5',
    title: 'Clutch save',
    game: 'League of Legends',
    duration: '0:52',
    size: '121 MB',
    ago: 'Yesterday',
    visibility: 'private',
    gradient: 'linear-gradient(145deg, #0f2438, #3d1a28)',
  },
  {
    id: 'c6',
    title: 'Team ace',
    game: 'Valorant',
    duration: '0:29',
    size: '76 MB',
    ago: 'Yesterday',
    visibility: 'public',
    gradient: 'linear-gradient(145deg, #2a1f3d, #1f3d2a)',
  },
]

export const discoverFeed = [
  {
    id: 'd1',
    title: 'Insane 1v5 Clutch',
    author: 'skyline',
    game: 'Valorant',
    views: '8.8k',
    likes: '1.2k',
    duration: '0:31',
    gradient: 'linear-gradient(135deg, #4a1f3d, #1e3a5c)',
  },
  {
    id: 'd2',
    title: 'Ceiling musty',
    author: 'vex',
    game: 'Rocket League',
    views: '5.1k',
    likes: '890',
    duration: '0:22',
    gradient: 'linear-gradient(135deg, #3d2a10, #1a2848)',
  },
  {
    id: 'd3',
    title: 'Zero build win',
    author: 'mira',
    game: 'Fortnite',
    views: '14k',
    likes: '2.1k',
    duration: '0:45',
    gradient: 'linear-gradient(135deg, #1f3d2d, #3d1f4a)',
  },
  {
    id: 'd4',
    title: 'Ace on defense',
    author: 'rift',
    game: 'CS2',
    views: '21k',
    likes: '3.4k',
    duration: '0:38',
    gradient: 'linear-gradient(135deg, #2d1f1f, #1a2d48)',
  },
  {
    id: 'd5',
    title: 'Squad wipe',
    author: 'nova',
    game: 'Apex',
    views: '6.2k',
    likes: '720',
    duration: '0:27',
    gradient: 'linear-gradient(135deg, #1a3d3d, #3d1a2a)',
  },
  {
    id: 'd6',
    title: 'Baron steal',
    author: 'fan',
    game: 'League',
    views: '9.9k',
    likes: '1.5k',
    duration: '1:02',
    gradient: 'linear-gradient(135deg, #2d3810, #1f1a3d)',
  },
]

export const GAME_FILTERS = [
  'All Games',
  'Valorant',
  'Rocket League',
  'Fortnite',
  'League of Legends',
  'CS2',
  'Apex Legends',
]
